version: "3.1"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7.31
    container_name: "musicai_mysql"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: diplomaSecret
      MYSQL_DATABASE: music
      MYSQL_USER: root
      MYSQL_PASSWORD: diplomaSecret
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "musicai_phpmyadmin"
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=diplomaSecret
    links:
      - mysql
    ports:
      - 8090:80

volumes:
  mysql:
